image: node:18

definitions:
  services:
    chrome:
      image: browserless/chrome

pipelines:
  default:
    - step:
        name: Install, Test & SonarCloud
        caches:
          - node
        services:
          - chrome
        script:
          # 1. Install dependencies
          - npm install

          # 2. Install Chrome for Karma Headless
          - apt-get update && apt-get install -y wget gnupg unzip
          - wget https://dl.google.com/linux/direct/google-chrome-stable_current_amd64.deb
          - apt-get install -y ./google-chrome-stable_current_amd64.deb || apt-get install -f -y

          # 3. Run Angular Unit Tests
          - npm run test -- --watch=false --browsers=ChromeHeadless

          # 4. Build Angular for production
          - npm run build -- --configuration production

          # 5. Run SonarCloud scan
          - node sonar.js