sonar.projectKey=bmecommerce_ecom-angular
sonar.organization=bmecommerce
sonar.sources=src
sonar.host.url=https://sonarcloud.io

# Optional: Include tests
sonar.tests=src
sonar.test.inclusions=**/*.spec.ts

# Coverage report path (Karma + Istanbul)
sonar.javascript.lcov.reportPaths=coverage/lcov.info
